### ISSUE TITLE
When added to a fabric server, I keep getting this error in my console. Works in SP.

### ISSUE THREAD

**Issue by Todredmi** [FirEmerald/DynamicVerticalSlabsAndStairs#101]
[03:45:33] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'additionalplacements' at 'com.firemerald.additionalplacements.common.CommonModEvents'!
        at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.5.jar:?]
        at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-launch.jar:1.0.1]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.networking.v1.ClientLoginNetworking$LoginQueryRequestHandler in environment type SERVER
        at com.firemerald.additionalplacements.network.APNetwork.registerClientLoginPacket(APNetwork.java:59) ~[additional-placements-fabric-1.20.1-2.1.0.jar:?]
        at com.firemerald.additionalplacements.network.APNetwork.register(APNetwork.java:43) ~[additional-placements-fabric-1.20.1-2.1.0.jar:?]
        at com.firemerald.additionalplacements.common.CommonModEvents.onInitialize(CommonModEvents.java:48) ~[additional-placements-fabric-1.20.1-2.1.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
        ... 7 more
Caused by: java.lang.RuntimeException: Cannot load class net.fabricmc.fabric.api.client.networking.v1.ClientLoginNetworking$LoginQueryRequestHandler in environment type SERVER
        at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.5.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.5.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at com.firemerald.additionalplacements.network.APNetwork.registerClientLoginPacket(APNetwork.java:59) ~[additional-placements-fabric-1.20.1-2.1.0.jar:?]
        at com.firemerald.additionalplacements.network.APNetwork.register(APNetwork.java:43) ~[additional-placements-fabric-1.20.1-2.1.0.jar:?]
        at com.firemerald.additionalplacements.common.CommonModEvents.onInitialize(CommonModEvents.java:48) ~[additional-placements-fabric-1.20.1-2.1.0.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.5.jar:?]
        ... 7 more
        
        
        Any ideas as to how I would be able to fix this? Server is on 1.20.1 for the moment, but once Cobblemon updates to 1.6 ill be going 1.21.

**Comment by FirEmerald** [comment]
_sigh_ I'll have to fix this. I tested it in MDK and it seemed to be fine but I guess I do still need those sided checks outside of it. Gotta find the right place to put them that doesn't break all the networking.
I hate Fabric's networking code, I really do.

**Comment by Todredmi** [comment]
I haven’t gotten into fabric modding; but I will take your word for it. I hope it’s a relatively easy fix however. The mod itself is absolutely great.

**Comment by FirEmerald** [comment]
Should be fixed in
834975c
c6d22c9
249b4de
e933e5f
9710947
428a0ce
