### ISSUE TITLE
Crashes on loading map from single to server

### ISSUE THREAD

**Issue by karasiks1488** [FirEmerald/DynamicVerticalSlabsAndStairs#86]
Crashes on loading map from single to server
Crash report here

---- Minecraft Crash Report ----
// My bad.

Time: 16.07.24, 21:06
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:120) ~[?:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {re:computing_frames}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[CatServer-1.16.5-69069a9c-server.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {re:classloading}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [CatServer-1.16.5-69069a9c-server.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [CatServer-1.16.5-69069a9c-server.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [CatServer-1.16.5-69069a9c-server.jar:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?] {re:computing_frames}
	at foxlaunch.FoxServerLauncher.main(FoxServerLauncher.java:33) [CatServer-1.16.5-69069a9c-server.jar:?] {}
	at catserver.server.CatServerLaunch.main(CatServerLaunch.java:8) [CatServer-1.16.5-69069a9c-server.jar:1.16.5-69069a9c] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:716) ~[?:?] {}
-- MOD additionalplacements --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
		at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
		at java.lang.Class.privateGetDeclaredConstructors(Class.java:3305) ~[?:?] {}
		at java.lang.Class.getConstructor0(Class.java:3510) ~[?:?] {}
		at java.lang.Class.getConstructor(Class.java:2238) ~[?:?] {}
		at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-4.0.0.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:263) ~[CatServer-1.16.5-69069a9c-server.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:256) ~[CatServer-1.16.5-69069a9c-server.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:150) ~[CatServer-1.16.5-69069a9c-server.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:78) ~[CatServer-1.16.5-69069a9c-server.jar:?] {}
		at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
		at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?] {}
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] {}
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] {}
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
		at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:78) ~[CatServer-1.16.5-69069a9c-server.jar:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[CatServer-1.16.5-69069a9c-server.jar:?] {}
		at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[forge:?] {re:classloading}
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
		at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[forge:?] {re:classloading}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[forge:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

	Mod File: AdditionalPlacements-1.16.5-1.8.0.jar
	Failure message: Additional Placements (additionalplacements) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraft/client/util/ITooltipFlag
	Mod Version: 1.8.0
	Mod Issue URL: https://github.com/FirEmerald/AdditionalPlacements/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraft.client.util.ITooltipFlag
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:716) ~[?:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:586) ~[?:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:519) ~[?:?] {}
	at java.lang.Class.getDeclaredConstructors0(Native Method) ~[?:?] {}
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:3305) ~[?:?] {}
	at java.lang.Class.getConstructor0(Class.java:3510) ~[?:?] {}
	at java.lang.Class.getConstructor(Class.java:2238) ~[?:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.computeListenerList(EventListenerHelper.java:96) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerListInternal(EventListenerHelper.java:63) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.api.EventListenerHelper.getListenerList(EventListenerHelper.java:48) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.addToListeners(EventBus.java:263) ~[CatServer-1.16.5-69069a9c-server.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:256) ~[CatServer-1.16.5-69069a9c-server.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.registerListener(EventBus.java:150) ~[CatServer-1.16.5-69069a9c-server.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$registerClass$2(EventBus.java:78) ~[CatServer-1.16.5-69069a9c-server.jar:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?] {}
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:?] {}
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?] {}
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?] {}
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?] {}
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?] {}
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?] {}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:78) ~[CatServer-1.16.5-69069a9c-server.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:118) ~[CatServer-1.16.5-69069a9c-server.jar:?] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[forge:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {}
	at net.minecraftforge.fml.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1800) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1792) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 6674047472 bytes (6364 MB) / 8589934592 bytes (8192 MB) up to 10737418240 bytes (10240 MB)
	CPUs: 16
	JVM Flags: 2 total; -Xms8G -Xmx10G
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/CatServer-1.16.5-69069a9c-server.jar object_holder_definalize PLUGINSERVICE 
		/CatServer-1.16.5-69069a9c-server.jar runtime_enum_extender PLUGINSERVICE 
		/CatServer-1.16.5-69069a9c-server.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/CatServer-1.16.5-69069a9c-server.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/CatServer-1.16.5-69069a9c-server.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		mcw-bridges-2.0.0-mc1.16.5.jar                    |Macaw's Bridges               |mcwbridges                    |2.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		betteranimalmodels-1.16.5-5.6.0-forge.jar         |Cyber's Better Animal Models  |betteranimalmodels            |1.16.5-5.6.0        |CREATE_REG|Manifest: NOSIGNATURE
		ShoulderSurfing-Forge-1.16.5-2.8.1.jar            |Shoulder Surfing              |shouldersurfing               |1.16.5-2.8.1        |CREATE_REG|Manifest: NOSIGNATURE
		player-animation-lib-forge-0.4.0+1.16.5.jar       |Player Animator               |playeranimator                |0.4.0+1.16.5        |CREATE_REG|Manifest: NOSIGNATURE
		mcw-fences-1.0.2-mc1.16.5.jar                     |Macaw's Fences and Walls      |mcwfences                     |1.0.2               |CREATE_REG|Manifest: NOSIGNATURE
		NaturalDecorMod_1.16.5_V1.2.2.jar                 |Natural Decor Mod             |naturaldecormod               |1.2.2               |CREATE_REG|Manifest: NOSIGNATURE
		AdditionalPlacements-1.16.5-1.8.0.jar             |Additional Placements         |additionalplacements          |1.8.0               |ERROR     |Manifest: NOSIGNATURE
		mcw-windows-2.2.1-mc1.16.5forge.jar               |Macaw's Windows               |mcwwindows                    |2.2.1               |CREATE_REG|Manifest: NOSIGNATURE
		CNB-1.16.3_5-1.2.11.jar                           |Creatures and Beasts          |cnb                           |1.2.11              |CREATE_REG|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.1.0.0.jar                   |Curios API                    |curios                        |1.16.5-4.1.0.0      |CREATE_REG|Manifest: NOSIGNATURE
		infusedring-1.16.5-1.0.4b.jar                     |Infused Ring Mod              |infusedring                   |1.0.4b              |CREATE_REG|Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.3.jar                         |Patchouli                     |patchouli                     |1.16.4-53.3         |CREATE_REG|Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                        |Waystones                     |waystones                     |7.6.4               |CREATE_REG|Manifest: NOSIGNATURE
		RPGMOD.jar                                        |F0restguy x renaissance RPG   |rpgmod                        |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		ForgeEndertech-1.16.5-7.3.0.0-build.0330.jar      |ForgeEndertech                |forgeendertech                |7.3.0.0             |CREATE_REG|Manifest: NOSIGNATURE
		EpicFightMod-16.5.13.jar                          |Epic Fight Mod                |epicfight                     |16.5.13             |CREATE_REG|Manifest: NOSIGNATURE
		mcw-paintings-1.0.5-1.16.5forge.jar               |Macaw's Paintings             |mcwpaintings                  |1.0.5               |CREATE_REG|Manifest: NOSIGNATURE
		moreenchantments_mc_1.16.4_vers.1.4.1.jar         |More Enchantments             |more_enchantments             |1.4.1               |CREATE_REG|Manifest: NOSIGNATURE
		Horror_elements_mod_1.5.5_1.16.5.jar              |Horror Element Mod            |horror_element_mod            |1.5.5               |CREATE_REG|Manifest: NOSIGNATURE
		configured-1.5.4-1.16.5.jar                       |Configured                    |configured                    |1.5.4               |CREATE_REG|Manifest: NOSIGNATURE
		armourersworkshop-forge-1.16.5-2.0.11.jar         |Armourer's Workshop           |armourers_workshop            |2.0.11              |CREATE_REG|Manifest: 58:d0:3b:4b:a0:4b:43:fb:59:0f:27:f5:39:d5:65:de:9a:24:ee:2e:15:48:b1:4f:78:1a:e1:ef:cd:a4:d9:0a
		betteranimalsplus-1.16.5-11.0.10-forge.jar        |Better Animals Plus           |betteranimalsplus             |1.16.5-11.0.10      |CREATE_REG|Manifest: NOSIGNATURE
		Bookshelf-Forge-1.16.5-10.4.33.jar                |Bookshelf                     |bookshelf                     |10.4.33             |CREATE_REG|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		CustomNPCs-1.16.5.20220515.jar                    |Custom NPCs                   |customnpcs                    |1.16.5.20220515     |CREATE_REG|Manifest: NOSIGNATURE
		mcw-doors-1.0.9forge-mc1.16.5.jar                 |Macaw's Doors                 |mcwdoors                      |1.0.9               |CREATE_REG|Manifest: NOSIGNATURE
		architectury-1.32.68-forge-1.16.5.jar             |Architectury                  |architectury                  |1.32.68             |CREATE_REG|Manifest: NOSIGNATURE
		additional_lights_1.16.4_2.1.3.jar                |Additional Lights             |additional_lights             |2.1.3               |CREATE_REG|Manifest: NOSIGNATURE
		mcw-furniture-3.2.0-mc1.16.5forge.jar             |Macaw's Furniture             |mcwfurnitures                 |3.2.0               |CREATE_REG|Manifest: NOSIGNATURE
		cloth-config-4.17.101-forge-1.16.5_1.jar          |Cloth Config v4 API           |cloth-config                  |4.17.101            |CREATE_REG|Manifest: NOSIGNATURE
		AdChimneys-1.16.5-6.1.0.0-build.0330.jar          |Advanced Chimneys             |adchimneys                    |6.1.0.0             |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |CREATE_REG|Manifest: NOSIGNATURE
		tinyinv-1.16.5-1.0.4.1.jar                        |Tiny Inv                      |tinyinv                       |1.16.5-1.0.4.1      |CREATE_REG|Manifest: NOSIGNATURE
		daily_rewards_1.16.5-1.0.0.jar                    |Daily Rewards                 |daily_rewards                 |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		Fish-s-Undead-Rising-2.3.0-1.16.5.jar             |Fish's Undead Rising          |mod_lavacow                   |2.3.0               |CREATE_REG|Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.870-universal.jar       |The Twilight Forest           |twilightforest                |NONE                |CREATE_REG|Manifest: NOSIGNATURE
		supplementaries-1.16.5-0.18.5.jar                 |Supplementaries               |supplementaries               |0.18.3              |CREATE_REG|Manifest: NOSIGNATURE
		geckolib-forge-1.16.5-3.0.106.jar                 |GeckoLib                      |geckolib3                     |3.0.106             |CREATE_REG|Manifest: NOSIGNATURE
		ars_nouveau-1.16.5-1.25.10.jar                    |Ars Nouveau                   |ars_nouveau                   |1.25.10             |CREATE_REG|Manifest: NOSIGNATURE
		morered-1.16.5-2.1.1.0.jar                        |More Red                      |morered                       |2.1.1.0             |CREATE_REG|Manifest: NOSIGNATURE
		emotecraft-for-MC1.16.5-2.2.7-b.build.47-forge.jar|Emotecraft                    |emotecraft                    |2.2.7-b.build.47    |CREATE_REG|Manifest: NOSIGNATURE
		selene-1.16.5-1.9.0.jar                           |Selene                        |selene                        |1.16.5-1.0          |CREATE_REG|Manifest: NOSIGNATURE
	Crash Report UUID: 6f6b3873-be16-4088-bbe4-175078364970
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport: craftbukkit not runs

**Comment by FirEmerald** [comment]
oh BTW this should be fixed as of 2.0.0 and newer
