### ISSUE TITLE
Crash on the latest version

### ISSUE THREAD

**Issue by vlad1m** [FirEmerald/DynamicVerticalSlabsAndStairs#94]
When trying to break a block modified by additional placements,the game crashes.Here's the log:

Reported exception thrown!
net.minecraft.ReportedException: Tesselating block model
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:64) ~[client-1.20.1-20230612.114412-srg.jar%23552!/:?]
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.redirect$zho000$injectStateToModelLocation(BlockRenderDispatcher.java:547) ~[client-1.20.1-20230612.114412-srg.jar%23552!/:?]
	at net.minecraft.client.renderer.block.BlockRenderDispatcher.renderBreakingTexture(BlockRenderDispatcher.java:56) ~[client-1.20.1-20230612.114412-srg.jar%23552!/:?]
	at net.minecraft.client.renderer.LevelRenderer.m_109599_(LevelRenderer.java:1316) ~[client-1.20.1-20230612.114412-srg.jar%23552!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109089_(GameRenderer.java:1126) ~[client-1.20.1-20230612.114412-srg.jar%23552!/:?]
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:909) ~[client-1.20.1-20230612.114412-srg.jar%23552!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23552!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23552!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[client-1.20.1.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.11.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.11.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.11.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.RenderType.m_110508_()" because "renderType" is null
	at com.firemerald.additionalplacements.client.BlockModelUtils.rotatedQuads(BlockModelUtils.java:220) ~[AdditionalPlacements-1.20-2.0.0.jar%23354!/:2.0.0]
	at com.firemerald.additionalplacements.client.BlockModelUtils.rotatedQuads(BlockModelUtils.java:243) ~[AdditionalPlacements-1.20-2.0.0.jar%23354!/:2.0.0]
	at com.firemerald.additionalplacements.client.models.BakedRotatedBlockModel.getQuads(BakedRotatedBlockModel.java:46) ~[AdditionalPlacements-1.20-2.0.0.jar%23354!/:2.0.0]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateWithAO(ModelBlockRenderer.java:80) ~[client-1.20.1-20230612.114412-srg.jar%23552!/:?]
	at net.minecraftforge.client.model.lighting.ForgeModelBlockRenderer.tesselateWithAO(ForgeModelBlockRenderer.java:65) ~[forge-1.20.1-47.3.11-universal.jar%23557!/:?]
	at net.minecraft.client.renderer.block.ModelBlockRenderer.tesselateBlock(ModelBlockRenderer.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23552!/:?]

**Comment by Sharaj00** [comment]
same
1.8.0 works fine

**Comment by FirEmerald** [comment]
Fixed as of 2.0.3 in:
1.19.2 forge: a947e6f4b21cd9bcb5b35329ddb815197d8a1027
1.19.4 forge: 88bf1421b2817b5b0932304d97c7e0752f8d5e23
1.20.1 forge: 3958c1ee8f2cba59e1a45b019bc8ee9033006e88
1.20.2 forge: 1d9e16eb4410dac02b1c496095ef15a935e7c889
1.20.4 forge: 8ac1842475484c8f3bddad2861c6d8d9b4ef1ea2
1.20.4 neoforge: 839d781392cfc6c0b33f4f971569ab5eac9a87a0
1.21 neoforge: d87b90886424657956aa10859245a3b23dd96aad
